name: CD Compute

on:
  push:
    branches:
      - "preprod"
      - "prod"

  workflow_dispatch:

jobs:
  initiate-deployment:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      AWS_REGION: eu-west-3

    steps:
      - uses: actions/checkout@v4.1.6

      - uses: actions/setup-java@v4.2.1
        with:
          java-version: '21'
          distribution: 'corretto'

      - run: chmod +x  ./gradlew

      - run: chmod +x .shell/publish_gen_to_maven_local.sh

      - name: Get deployment required uris
        run: |
          response=$(curl -X GET "https://api.preprod.jcloudify.com/gh-repos/${{ github.repository }}/upload-build-uri?environment_type=$(echo "${{ github.ref_name }}" | tr '[:lower:]' '[:upper:]')" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/json")
          echo "build_template_file_uri=$(echo $response | jq -r '.build_template_file_uri')" >> $GITHUB_ENV
          echo "upload_build_file_uri=$(echo $response | jq -r '.uri')" >> $GITHUB_ENV
          echo "to_upload_filename=$(echo $response | jq -r '.filename')" >> $GITHUB_ENV

      - name: Download template.yml file
        run: |
          curl -X GET -o template.yml "${{ env.build_template_file_uri }}"

      - name: Build project
        run: sam build

      - name: Zip build folder
        run: |
          shopt -s globstar
          zip -r9 ${{ env.to_upload_filename }} .aws-sam
          shopt -u globstar

      - name: Upload zipped build file to s3
        run: |
          curl -X PUT -H "Content-Type: application/zip" -T ${{ env.to_upload_filename }} "${{ env.upload_build_file_uri }}"

      - name: Get current time
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Create UUID
        id: generate-uuid
        uses: filipstefansson/uuid-action@v1
        with:
          name: ${{ steps.current-time.outputs.time }}

      - name: Trigger app deployment
        run: |
          curl --fail -X PUT "https://api.preprod.jcloudify.com/gh-repos/${{ github.repository }}/env-deploys?environment_type=$(echo "${{ github.ref_name }}" | tr '[:lower:]' '[:upper:]')" \
                -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                -H "Content-Type: application/json" \
                -d "{\"formatted_bucket_key\":\"${{ env.to_upload_filename }}\",\"id\":\"${{ steps.generate-uuid.outputs.uuid }}\",\"environment_type\":$(echo \"${{ github.ref_name }}\" | tr \"[:lower:]\" \'[:upper:]\")}"
